local icons = {
  plus = "",
  loading = "󰑓",
  apple = "󰀵",
  gear = "",
  cpu = "󰻠",
  ram = "󰘚",
  clipboard = "󰅍",
  qq = "",
  wechat = "󰘑",
  brew = "󰏗",
  brew_check = "",

  switch = {
    on = "󰔡",
    off = "󰨙",
  },
  volume = {
    _100 = "󰕾",
    _66 = "󰖀",
    _33 = "󰕿",
    _10 = "󰕿",
    _0 = "󰝟",
  },
  battery = {
    _100 = "󰁹",
    _75 = "󰂁",
    _50 = "󰁾",
    _25 = "󰁻",
    _0 = "󰂎",
    charging = "󰂄",
    charging_10 = "󰢜",
    charging_20 = "󰂆",
    charging_30 = "󰂇",
    charging_40 = "󰂈",
    charging_50 = "󰢝",
    charging_60 = "󰂉",
    charging_70 = "󰢞",
    charging_80 = "󰂊",
    charging_90 = "󰂋",
    charging_100 = "󰂅",
  },
  wifi = {
    upload = "󰁝",
    download = "󰁅",
    connected = "󰤨",
    disconnected = "󰤭",
    router = "󰑩",
  },
  stats_toggle = {
    show = "",
    hide = "",
  },
  network = "󰛳",
  disk = "󰋊",
  power_menu = "󰤄",
  media = {
    play = "󰐊",
    pause = "󰏤",
    back = "󰒮",
    forward = "󰒭",
    repeating = "󰑖",
    shuffle = "󰒟",
  },
}

return icons
